### PR TITLE
Formatted document with prettier and editor config

### PR DESCRIPTION
**Pull request by kothariji**
# Description
Formatted the document with Prettier and EditorConfigs
command - `npx prettier --write . `

## Type of change

just formattings

### CODE REVIEW

**Review by akash-salvi — APPROVED** [review]
LGTM :+1:

**Review by kothariji — COMMENTED** [review]
Green Signal 🟢  from my End 🚩

**Review by maneprajakta — APPROVED** [review]
Don't know about .js files rest all seems okay :rocket: 
smile

**Comment by kothariji** [comment]
#5 Merged

**Pull request merged**
