### PR TITLE
Backend formatting and linting

### PR DESCRIPTION
**Pull request by kothariji**
Added Autopep8 and Flake8  for linting purposes and Isort for Sorting imports.

These dependencies help in maintaining code formatting for all 4 of us, with no blank lines, random white spaces, etc.

# Steps to follow:

## 1. `pip install -r requirements-dev.txt `

This will install both requirements as well as dev-requirements.

**Reason** - So autopep8 and flake8 are development dependencies, we don't need them in production. So adding them to our main requirements.txt will unnecessarily increase the build size, nothing else.

So we are using `pip install -r requirements-dev.txt` in our local, which will fulfill our both needs.

## 2. We use pre-commit git hook

install pre-commit using the `pip install pre-commit` command

then, initialize it using
`pre-commit install`

What it will do is, it will automatically run autopep8 and flake8, when you commit something in Github

### Screenshot
image

## 3. Install isort
Isort is a Python utility/library to sort imports alphabetically and automatically separated into sections and by type.

### Updates 
Install flake8 globally using command
`python -m pip install flake8`

Then run on any backend folder by running
```
cd backend
flake8
```

### CODE REVIEW

**Review by maneprajakta — APPROVED** [review]
Good to go :rocket: :+1:

**Comment by kothariji** [comment]
> Good to go 🚀 👍

Wooooo 🙌  🎉

**Review by akash-salvi — APPROVED** [review]
LGTM :+1:

**Comment by kothariji** [comment]
> LGTM 👍

Yayy🎉

**Pull request merged**
